/**
 * Code Krafter's - Fast Food & Beverages Menu Dataset
 * Curated high-res imagery, authentic pricing, savings & dietary indicators
 */

const MENU_CATEGORIES = [
  { id: 'all', name: '🔥 All Items', icon: '🔥', count: 35 },
  { id: 'burgers', name: '🍔 Krafter Burgers', icon: '🍔', count: 6 },
  { id: 'chicken', name: '🍗 Crispy Chicken', icon: '🍗', count: 6 },
  { id: 'pizzas', name: '🍕 Craft Pizzas', icon: '🍕', count: 5 },
  { id: 'sides', name: '🍟 Loaded Fries & Sides', icon: '🍟', count: 6 },
  { id: 'beverages', name: '🥤 Shakes & Drinks', icon: '🥤', count: 6 },
  { id: 'desserts', name: '🍨 Sweet Treats', icon: '🍨', count: 3 },
  { id: 'combos', name: '🍱 Value Meal Boxes', icon: '🍱', count: 3 }
];

const MENU_ITEMS = [
  // 1. BURGERS
  {
    id: 'b-1',
    name: "Code Krafter's Double Smash Byte",
    category: 'burgers',
    price: 249,
    originalPrice: 349,
    rating: 4.9,
    reviews: 1420,
    badge: 'Bestseller',
    badgeColor: '#FF2A4D',
    isVeg: false,
    calories: '680 kcal',
    prepTime: '12-15 mins',
    description: 'Double grilled smash patties topped with molten American cheddar, caramelized onions, secret krafter sauce on a toasted brioche bun.',
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'b-2',
    name: 'Fiery Peri-Peri Zinger Tower',
    category: 'burgers',
    price: 229,
    originalPrice: 299,
    rating: 4.8,
    reviews: 980,
    badge: 'Spicy 🔥',
    badgeColor: '#FF6B00',
    isVeg: false,
    calories: '620 kcal',
    prepTime: '10-12 mins',
    description: 'Extra crunchy fried chicken breast dunked in fiery peri-peri marinade, fresh iceberg lettuce, and spicy jalapeño mayo.',
    image: 'https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'b-3',
    name: 'Truffle Mushroom Glitch Burger',
    category: 'burgers',
    price: 279,
    originalPrice: 389,
    rating: 4.9,
    reviews: 620,
    badge: "Chef's Special ⭐",
    badgeColor: '#9D00FF',
    isVeg: false,
    calories: '710 kcal',
    prepTime: '15 mins',
    description: 'Charbroiled beef patty infused with wild truffle mushroom ragout, melted Swiss cheese, and garlic black pepper aioli.',
    image: 'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'b-4',
    name: 'Crispy Royale Golden Chicken',
    category: 'burgers',
    price: 199,
    originalPrice: 269,
    rating: 4.7,
    reviews: 840,
    badge: 'Popular',
    badgeColor: '#00E599',
    isVeg: false,
    calories: '550 kcal',
    prepTime: '10 mins',
    description: 'Golden fried chicken fillet coated in krafter 11-spice herb blend, crunchy gherkins, creamy mayo on a sesame seed bun.',
    image: 'https://images.unsplash.com/photo-1625813506062-0aeb1d7a094b?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'b-5',
    name: 'Garden Veggie Supreme Stack',
    category: 'burgers',
    price: 179,
    originalPrice: 239,
    rating: 4.7,
    reviews: 530,
    badge: '100% Veg 🥬',
    badgeColor: '#10B981',
    isVeg: true,
    calories: '480 kcal',
    prepTime: '10 mins',
    description: 'Crispy spiced potato, corn & herb patty layered with fresh tomatoes, red onion rings, cheddar slice, and mint mayo.',
    image: 'https://images.unsplash.com/photo-1520072959219-c595dc870360?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'b-6',
    name: 'Smoky BBQ Baconator Byte',
    category: 'burgers',
    price: 269,
    originalPrice: 359,
    rating: 4.8,
    reviews: 740,
    badge: 'Smoky & Bold',
    badgeColor: '#E11D48',
    isVeg: false,
    calories: '740 kcal',
    prepTime: '12 mins',
    description: 'Juicy double patty stacked with crispy smoked strips, melted aged cheddar, tangy hickory BBQ drizzle, and crispy onion strings.',
    image: 'https://images.unsplash.com/photo-1553979459-d2229ba7433b?auto=format&fit=crop&w=800&q=80'
  },

  // 2. CRISPY CHICKEN & BUCKETS
  {
    id: 'c-1',
    name: 'Krafter 8-Piece Golden Bucket',
    category: 'chicken',
    price: 499,
    originalPrice: 699,
    rating: 4.9,
    reviews: 2150,
    badge: 'Bucket Special 🍗',
    badgeColor: '#FF2A4D',
    isVeg: false,
    calories: '1180 kcal',
    prepTime: '15-18 mins',
    description: '8 pieces of signature ultra-crispy, juicy pressure-fried chicken prepared with our secret 14-spice blend. Served with 2 dips.',
    image: 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'c-2',
    name: 'Fiery Krafter Hot Wings (6 Pcs)',
    category: 'chicken',
    price: 219,
    originalPrice: 289,
    rating: 4.8,
    reviews: 1320,
    badge: 'Hot Pick 🌶️',
    badgeColor: '#FF6B00',
    isVeg: false,
    calories: '520 kcal',
    prepTime: '10-12 mins',
    description: 'Crunchy chicken wings tossed in our signature Nashville ghost pepper glaze, garnished with toasted sesame and scallions.',
    image: 'https://images.unsplash.com/photo-1567620832903-9fc6debc209f?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'c-3',
    name: 'Popcorn Chicken Bites Tub',
    category: 'chicken',
    price: 169,
    originalPrice: 229,
    rating: 4.7,
    reviews: 1890,
    badge: 'Snack Attack',
    badgeColor: '#FFB800',
    isVeg: false,
    calories: '420 kcal',
    prepTime: '8 mins',
    description: 'Bite-sized tender boneless chicken morsels seasoned with rock salt, peri-peri dust, and served with spicy chipotle dip.',
    image: 'https://images.unsplash.com/photo-1562967914-608f82629710?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'c-4',
    name: 'Smoky BBQ Glazed Drumsticks (4 Pcs)',
    category: 'chicken',
    price: 289,
    originalPrice: 389,
    rating: 4.8,
    reviews: 950,
    badge: 'Finger Lickin',
    badgeColor: '#B91C1C',
    isVeg: false,
    calories: '610 kcal',
    prepTime: '12 mins',
    description: 'Tender jumbo chicken drumsticks flame-glazed with sticky bourbon honey BBQ sauce, smoked over hickory woodchips.',
    image: 'https://images.unsplash.com/photo-1527477378676-4d2a32707135?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'c-5',
    name: 'Crispy Tender Strips (5 Pcs)',
    category: 'chicken',
    price: 239,
    originalPrice: 319,
    rating: 4.8,
    reviews: 790,
    badge: '100% Breast Meat',
    badgeColor: '#00E599',
    isVeg: false,
    calories: '460 kcal',
    prepTime: '10 mins',
    description: 'Crispy buttermilk battered boneless chicken strips, golden fried to tender perfection. Served with honey mustard sauce.',
    image: 'https://images.unsplash.com/photo-1569058242253-92a9c755a0ec?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'c-6',
    name: 'Spicy Peri-Peri Chicken Strips Tub',
    category: 'chicken',
    price: 249,
    originalPrice: 329,
    rating: 4.7,
    reviews: 610,
    badge: 'Zesty Dip',
    badgeColor: '#E11D48',
    isVeg: false,
    calories: '490 kcal',
    prepTime: '10 mins',
    description: 'Panko crumbed boneless tenders dusted in fiery African bird’s eye chili spice with cool mint garlic dip.',
    image: 'https://images.unsplash.com/photo-1587314168485-3236d6710814?auto=format&fit=crop&w=800&q=80'
  },

  // 3. CRAFT PAN PIZZAS
  {
    id: 'p-1',
    name: 'Pepperoni Overdrive Pan Pizza',
    category: 'pizzas',
    price: 349,
    originalPrice: 479,
    rating: 4.9,
    reviews: 1680,
    badge: 'All-Time Classic',
    badgeColor: '#FF2A4D',
    isVeg: false,
    calories: '890 kcal',
    prepTime: '15-18 mins',
    description: 'Loaded edge-to-edge with spicy pepperoni slices, 100% mozzarella cheese blend, Italian herb marinara on a buttery pan crust.',
    image: 'https://images.unsplash.com/photo-1628840042765-356cda07504e?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'p-2',
    name: 'Margherita Supreme Double Cheese',
    category: 'pizzas',
    price: 279,
    originalPrice: 369,
    rating: 4.8,
    reviews: 1410,
    badge: '100% Veg 🧀',
    badgeColor: '#10B981',
    isVeg: true,
    calories: '760 kcal',
    prepTime: '12-14 mins',
    description: 'Rich San Marzano tomato sauce, generous double mozzarella, cherry tomatoes, fresh basil leaves, and extra virgin olive oil drizzle.',
    image: 'https://images.unsplash.com/photo-1604382355076-af4b0eb60143?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'p-3',
    name: 'Fiery Tandoori Paneer Tikka Pizza',
    category: 'pizzas',
    price: 319,
    originalPrice: 429,
    rating: 4.8,
    reviews: 1190,
    badge: 'Desi Fusion',
    badgeColor: '#FF6B00',
    isVeg: true,
    calories: '820 kcal',
    prepTime: '15 mins',
    description: 'Tandoor-charred spiced paneer cubes, crunchy bell peppers, red onions, spicy coriander-mint pesto drizzle, and melted cheese.',
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'p-4',
    name: 'Smoky BBQ Krafter Chicken Pizza',
    category: 'pizzas',
    price: 369,
    originalPrice: 499,
    rating: 4.9,
    reviews: 1350,
    badge: 'Meat Lovers',
    badgeColor: '#9D00FF',
    isVeg: false,
    calories: '920 kcal',
    prepTime: '15-18 mins',
    description: 'BBQ smoked shredded chicken, bacon bits, red onions, charred bell peppers, smoky chipotle drizzle on cheese burst crust.',
    image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'p-5',
    name: 'Cheesy Garlic Crust Diablo',
    category: 'pizzas',
    price: 329,
    originalPrice: 439,
    rating: 4.7,
    reviews: 640,
    badge: 'Cheese Burst',
    badgeColor: '#FFB800',
    isVeg: true,
    calories: '850 kcal',
    prepTime: '14 mins',
    description: 'Garlic butter brushed stuffed cheese crust, jalapeños, black olives, paprika chili flakes, and triple melted cheese blend.',
    image: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=800&q=80'
  },

  // 4. LOADED FRIES & SIDES
  {
    id: 's-1',
    name: 'Cheesy Lava Volcano Loaded Fries',
    category: 'sides',
    price: 189,
    originalPrice: 249,
    rating: 4.9,
    reviews: 2310,
    badge: 'Fan Favorite 🧀',
    badgeColor: '#FFB800',
    isVeg: true,
    calories: '580 kcal',
    prepTime: '8 mins',
    description: 'Golden crispy skin-on french fries drenched in hot liquid cheddar cheese lava, jalapeños, spring onions, and signature krafter spice.',
    image: 'https://images.unsplash.com/photo-1585109649139-366815a0d713?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 's-2',
    name: 'Cajun Seasoned Waffle Fries',
    category: 'sides',
    price: 149,
    originalPrice: 199,
    rating: 4.8,
    reviews: 1120,
    badge: 'Extra Crisp',
    badgeColor: '#FF6B00',
    isVeg: true,
    calories: '440 kcal',
    prepTime: '6 mins',
    description: 'Crispy lattice-cut waffle fries tossed in authentic New Orleans cajun herb spice. Served with tangy garlic ranch.',
    image: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 's-3',
    name: 'Golden Onion Crunch Rings',
    category: 'sides',
    price: 139,
    originalPrice: 189,
    rating: 4.7,
    reviews: 890,
    badge: 'Crunch King',
    badgeColor: '#F59E0B',
    isVeg: true,
    calories: '390 kcal',
    prepTime: '6-8 mins',
    description: 'Thick sliced sweet white onions battered in craft beer crumb batter, fried extra golden crisp with smoky cocktail sauce.',
    image: 'https://images.unsplash.com/photo-1639024471287-032f66705664?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 's-4',
    name: 'Molten Jalapeño Cheese Poppers (6 Pcs)',
    category: 'sides',
    price: 169,
    originalPrice: 229,
    rating: 4.8,
    reviews: 1430,
    badge: 'Cheese Bomb 💣',
    badgeColor: '#FF2A4D',
    isVeg: true,
    calories: '480 kcal',
    prepTime: '7 mins',
    description: 'Crispy herb-crusted sphere bites filled with spicy jalapeño bits and rich melted cream cheese that bursts in your mouth.',
    image: 'https://images.unsplash.com/photo-1541592106381-b31e9677c0e5?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 's-5',
    name: 'Peri-Peri Chicken Loaded Fries',
    category: 'sides',
    price: 219,
    originalPrice: 299,
    rating: 4.9,
    reviews: 1780,
    badge: 'Ultimate Loaded',
    badgeColor: '#E11D48',
    isVeg: false,
    calories: '690 kcal',
    prepTime: '10 mins',
    description: 'Crispy golden fries crowned with shredded spicy chicken, melted mozzarella, peri-peri mayonnaise, and crispy jalapeño chips.',
    image: 'https://images.unsplash.com/photo-1576107232684-1279f3908594?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 's-6',
    name: 'Gourmet Krafter Dip Trio Box',
    category: 'sides',
    price: 89,
    originalPrice: 129,
    rating: 4.8,
    reviews: 620,
    badge: 'Add-on',
    badgeColor: '#00E599',
    isVeg: true,
    calories: '180 kcal',
    prepTime: '2 mins',
    description: 'Three chef-crafted signature sauces: Truffle Garlic Aioli, Fiery Ghost Chili Mayo, and Sweet Smoky Bourbon Mustard.',
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80'
  },

  // 5. SHAKES & BEVERAGES
  {
    id: 'd-1',
    name: 'Oreo Krafter Mega Thickshake',
    category: 'beverages',
    price: 179,
    originalPrice: 239,
    rating: 4.9,
    reviews: 2480,
    badge: 'Top Beverage 🥤',
    badgeColor: '#00E599',
    isVeg: true,
    calories: '520 kcal',
    prepTime: '5 mins',
    description: 'Thick handcrafted shake blended with whole Oreo cookies, Belgian chocolate ice cream, topped with whipped cream and crushed oreos.',
    image: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'd-2',
    name: 'Lotus Biscoff Caramel Shake',
    category: 'beverages',
    price: 199,
    originalPrice: 269,
    rating: 4.9,
    reviews: 1840,
    badge: 'Trending ⭐',
    badgeColor: '#FFB800',
    isVeg: true,
    calories: '560 kcal',
    prepTime: '5 mins',
    description: 'Creamy indulgence with crunchy caramelized Biscoff spread, vanilla bean cream, caramel drizzle, and speculoos cookie crumble.',
    image: 'https://images.unsplash.com/photo-1541658016709-82535e94bc69?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'd-3',
    name: 'Electric Blue Citrus Sparkler',
    category: 'beverages',
    price: 139,
    originalPrice: 189,
    rating: 4.7,
    reviews: 1120,
    badge: 'Refreshing ⚡',
    badgeColor: '#06B6D4',
    isVeg: true,
    calories: '160 kcal',
    prepTime: '3 mins',
    description: 'Fizzy Blue Curacao infused with fresh lime zest, cooling mint sprigs, and bubbling carbonated soda with crushed ice.',
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'd-4',
    name: 'Retro Vanilla Cola Ice Cream Float',
    category: 'beverages',
    price: 129,
    originalPrice: 179,
    rating: 4.8,
    reviews: 950,
    badge: 'Classic 🍦',
    badgeColor: '#8B5CF6',
    isVeg: true,
    calories: '280 kcal',
    prepTime: '3 mins',
    description: 'Chilled bubbly cola crowned with a giant scoop of rich Madagascar vanilla bean ice cream and maraschino cherry.',
    image: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'd-5',
    name: 'Fresh Mint Lime Cooler Mojito',
    category: 'beverages',
    price: 119,
    originalPrice: 159,
    rating: 4.7,
    reviews: 820,
    badge: 'Zero Sugar Option',
    badgeColor: '#10B981',
    isVeg: true,
    calories: '110 kcal',
    prepTime: '3 mins',
    description: 'Freshly muddled garden mint, zesty kaffir lime wedges, raw cane sugar, and sparkling soda served ice cold.',
    image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'd-6',
    name: 'Wild Strawberry & Cream Shake',
    category: 'beverages',
    price: 169,
    originalPrice: 229,
    rating: 4.8,
    reviews: 1040,
    badge: 'Fruity Bliss',
    badgeColor: '#EC4899',
    isVeg: true,
    calories: '450 kcal',
    prepTime: '5 mins',
    description: 'Real strawberry purée blended with velvety vanilla ice cream, topped with pink sprinkles and strawberry coulis drizzle.',
    image: 'https://images.unsplash.com/photo-1579954115545-a95591f28bfc?auto=format&fit=crop&w=800&q=80'
  },

  // 6. SWEET TREATS & DESSERTS
  {
    id: 'sw-1',
    name: 'Hot Molten Choco Lava Volcano',
    category: 'desserts',
    price: 149,
    originalPrice: 199,
    rating: 4.9,
    reviews: 2890,
    badge: 'Sinful Dessert 🍫',
    badgeColor: '#FF2A4D',
    isVeg: true,
    calories: '420 kcal',
    prepTime: '6 mins',
    description: 'Warm chocolate sponge cake with an oozing liquid dark fudge center. Dusted with powdered icing sugar.',
    image: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'sw-2',
    name: 'Crispy Warm Apple Cinnamon Pie',
    category: 'desserts',
    price: 129,
    originalPrice: 169,
    rating: 4.8,
    reviews: 1340,
    badge: 'Warm & Crispy',
    badgeColor: '#F59E0B',
    isVeg: true,
    calories: '310 kcal',
    prepTime: '5 mins',
    description: 'Flaky golden puff pastry turnover packed with spiced Granny Smith apple compote and warm Ceylon cinnamon glaze.',
    image: 'https://images.unsplash.com/photo-1568571780765-9276ac8b75a2?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'sw-3',
    name: 'Choco Nut Fudge Sundae Bowl',
    category: 'desserts',
    price: 159,
    originalPrice: 219,
    rating: 4.8,
    reviews: 1110,
    badge: 'Loaded Sundae',
    badgeColor: '#8B5CF6',
    isVeg: true,
    calories: '460 kcal',
    prepTime: '4 mins',
    description: 'Triple scoops of vanilla & chocolate swirl ice cream, hot chocolate fudge fountain, roasted cashew nuts, and wafer stick.',
    image: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?auto=format&fit=crop&w=800&q=80'
  },

  // 7. MEGA VALUE MEAL BOXES
  {
    id: 'cm-1',
    name: "Gamer's All-Nighter Box",
    category: 'combos',
    price: 449,
    originalPrice: 689,
    rating: 4.9,
    reviews: 3200,
    badge: 'Save ₹240 🔥',
    badgeColor: '#FF2A4D',
    isVeg: false,
    calories: '1420 kcal',
    prepTime: '15 mins',
    description: '1 Double Smash Burger + 3 Crispy Hot Wings + 1 Cheesy Lava Fries + 1 Chilled Cola + 1 Chocolate Lava Cake!',
    image: 'https://images.unsplash.com/photo-1594212699903-ec8a3eca50f5?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'cm-2',
    name: 'Krafter Duo Feast Meal Box',
    category: 'combos',
    price: 599,
    originalPrice: 899,
    rating: 4.9,
    reviews: 2140,
    badge: 'For 2 People 👥',
    badgeColor: '#00E599',
    isVeg: false,
    calories: '1680 kcal',
    prepTime: '18 mins',
    description: '2 Crispy Royale Burgers + 4 Crispy Tenders + 1 Medium Pepperoni Pizza + 2 Thickshakes + 2 Gourmet Dips.',
    image: 'https://images.unsplash.com/photo-1561758033-d89a9ad46330?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'cm-3',
    name: 'Big Family Krafter Party Bucket Box',
    category: 'combos',
    price: 999,
    originalPrice: 1499,
    rating: 5.0,
    reviews: 4100,
    badge: 'Save ₹500 🏆',
    badgeColor: '#FFB800',
    isVeg: false,
    calories: '2800 kcal',
    prepTime: '20 mins',
    description: '8 Pcs Golden Fried Chicken + 2 Krafter Burgers + 1 Large Cheese Pizza + 2 Loaded Waffle Fries + 4 Beverages + 2 Choco Lavas!',
    image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=800&q=80'
  }
];

// Available coupon codes
const PROMO_COUPONS = {
  'KRAFTER50': {
    code: 'KRAFTER50',
    discountPercent: 50,
    maxDiscount: 150,
    minOrder: 299,
    description: '50% OFF up to ₹150 on orders above ₹299'
  },
  'BYTEBITE': {
    code: 'BYTEBITE',
    flatDiscount: 100,
    minOrder: 399,
    description: 'Flat ₹100 OFF on orders above ₹399'
  },
  'FREEDEL': {
    code: 'FREEDEL',
    freeDelivery: true,
    minOrder: 199,
    description: 'Free Fast Delivery on orders above ₹199'
  }
};
